export default [ 
    {
      name: 'Bloody Hoodie',
      price: '35',
      pic1: '/shopImages/Temp/bloodFront.png',
      pic2: '/shopImages/temp/bloodBack.png',
      pic3: null,
      pic4: null,
      pic5: null,
      pic6: null,
      descr: 'Hopped on the Dexter wave with this one. Now you can look stylish in white and eat shit at the skatepark because this hoodie looks even cooler dirty and stained. \n "bloody fuck you bloody, fucking mother bloody fuck bitch" \n  - angry guy in car \n 100% Cotton \n Heat Transfer Vinyl and Acrylic Paint \nHandmade in Denver CO \n WASHING INSTRUCTIONS: \n To make it last the longest, turn the shirt inside out and wash on cold, then air dry. I know that\'s a hassle but at least wash on cold, you should do that with all your clothes anyway. \n ',
      id: 'blood',
      decimalPrice: 35.00,
      oneSided: true
    },
    {
      name: 'Demon Buddy',
      price: '35',
      pic1: '/shopImages/Temp/DemonFront.png',
      pic2: '/shopImages/temp/DemonBack.png',
      pic3: null,
      pic4: null,
      pic5: null,
      pic6: null,
      descr: 'Bro’s just tryna smoke please leave him alone. Put some eye’s on the hood so you can watch all angles. \n 100% Cotton \n  Heat Transfer Vinyl \n Handmade in Denver CO \n WASHING INSTRUCTIONS: \n  To make it last the longest, turn the shirt inside out and wash on cold, then air dry. I know that\'s a hassle but at least wash on cold, you should do that with all your clothes anyway. \n', 
      id: 'demon',
      decimalPrice: 35.00,
      oneSided: true
    },
    {
      name: 'Collage Hat',
      price: '120',
      pic1: '/shopImages/Temp/hat1.png',
      pic2: '/shopImages/temp/hat2.png',
      pic3: '/shopImages/temp/hat3.png',
      pic4: '/shopImages/temp/hat4.png',
      pic5: null,
      pic6: null,
      descr: 'Smoked a few blunts and started cutting shit in my house, this is the final result. \n 100% Cotton \n Multi Media / whatever I could find \n Handmade in Denver CO \n WASHING INSTRUCTIONS: \n  To make it last the longest, turn the shirt inside out and wash on cold, then air dry. I know that\'s a hassle but at least wash on cold, you should do that with all your clothes anyway. \n ',
      id: 'hat',
      decimalPrice: 120.00,
      oneSided: true
    },
    {
      name: 'Sparkle Pants',
      price: '100',
      pic1: '/shopImages/Temp/SparklePant.png',
      pic2: '/shopImages/temp/SparkleBack.png',
      pic3: null,
      pic4: null,
      pic5: null,
      pic6: null,
      descr: 'Shiny! \n Size? \n  Embroidery \n Handmade in Denver CO \n WASHING INSTRUCTIONS: \n  To make it last the longest, turn the shirt inside out and wash on cold, then air dry. I know that\'s a hassle but at least wash on cold, you should do that with all your clothes anyway. \n ',
      id: 'shiny',
      decimalPrice: 100.00,
      oneSided: true
    },
    {
      name: 'Penguin Hoodie',
      price: '40',
      pic1: '/shopImages/Temp/PenguinBack.png',
      pic2: '/shopImages/temp/penguin1.jpg',
      pic3: null,
      pic4: null,
      pic5: null,
      pic6: null,
      descr: 'I hate when this happens, no ciggy 4 pingu :( \n 100% Cotton \n  Heat Transfer Vinyl and Acrylic Paint \n Handmade in Denver CO \n WASHING INSTRUCTIONS: \n  To make it last the longest, turn the shirt inside out and wash on cold, then air dry. I know that\'s a hassle but at least wash on cold, you should do that with all your clothes anyway. \n ',
      id: 'pingu',
      decimalPrice: 40.00,
      oneSided: true
    },
    {
      name: 'Corduroy',
      price: '150',
      pic1: '/shopImages/Temp/nuri.png',
      pic2: null,
      pic3: null,
      pic4: null,
      pic5: null,
      pic6: null,
      descr: 'yah \n 100% Cotton \n  Heat Transfer Vinyl and Acrylic Paint \n Handmade in Denver CO \n WASHING INSTRUCTIONS: \n  To make it last the longest, turn the shirt inside out and wash on cold, then air dry. I know that\'s a hassle but at least wash on cold, you should do that with all your clothes anyway. \n ',
      id: 'green',
      decimalPrice: 150.00,
      oneSided: false
    },
    {
      name: 'Logo Shirt White',
      price: '20',
      pic1: '/shopImages/Temp/nuri.png',
      pic2: null,
      pic3: null,
      pic4: null,
      pic5: null,
      pic6: null,
      descr: 'It\'s a shirt with the logo, and it\'s white. Not much else to say, totally buy one though. \n 100% Cotton \n  Heat Transfer Vinyl and Acrylic Paint \n Handmade in Denver CO \n WASHING INSTRUCTIONS: \n  To make it last the longest, turn the shirt inside out and wash on cold, then air dry. I know that\'s a hassle but at least wash on cold, you should do that with all your clothes anyway. \n  ',
      id: 'logowhite',
      decimalPrice: 20.00,
      oneSided: true
    },
    {
      name: 'Logo Shirt Black',
      price: '20',
      pic1: '/shopImages/Temp/nuri.png',
      pic2: null,
      pic3: null,
      pic4: null,
      pic5: null,
      pic6: null,
      descr: 'It\'s a shirt with the logo, and it\'s white. Not much else to say, totally buy one though. \n 100% Cotton \n  Heat Transfer Vinyl and Acrylic Paint \n Handmade in Denver CO \n WASHING INSTRUCTIONS: \n  To make it last the longest, turn the shirt inside out and wash on cold, then air dry. I know that\'s a hassle but at least wash on cold, you should do that with all your clothes anyway. \n  ',
      id: 'logoblack',
      decimalPrice: 20.00,
      oneSided: true
    }
    

  ]